### ISSUE TITLE
Sqlite Version in CMake does not match source

### ISSUE THREAD

**Issue by kaihowl** [hunter-packages/sqlite3#1]
https://github.com/hunter-packages/sqlite3/blob/hunter-3.24.0/CMakeLists.txt#L2 reads 3.21.0 as a version. The checked in source files have a SQLITE_VERSION of 3.24.0, though. Am I misinterpreting the setup or should the CMake file be updated?

**Comment by ruslo** [comment]
> should the CMake file be updated

Yes, CMake code is out of date, it was cherry-picked from previous 3.21.0 release.

Hunter release with fixed version: https://github.com/ruslo/hunter/releases/tag/v0.23.61
